namespace Roslyn.Generator
{
	internal partial class HelloWorldGenerator
	{
		private const string HelloWorldAttribute = @"// <auto-generated/>
#nullable enable

namespace Roslyn.Generated
{
	[global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
	internal sealed class HelloWorldAttribute : global::System.Attribute
	{
	}
}
";
	}
}
