#if (!Roslyn3_8 && !Roslyn3_9 && !Roslyn4_0 && !Roslyn4_2)
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Roslyn.Generator
{
	[Generator(LanguageNames.CSharp)]
	internal sealed partial class HelloWorldGenerator : IIncrementalGenerator
	{
		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			const string helloWorldAttributeName = "Roslyn.Generated.HelloWorldAttribute";

			context.RegisterPostInitializationOutput(PostInitializationCallback);

			IncrementalValuesProvider<IGrouping<TypeDeclarationSyntax, (MethodDeclarationSyntax node, IMethodSymbol symbol)>> provider = context.SyntaxProvider
				.ForAttributeWithMetadataName(helloWorldAttributeName, SyntaxProviderPredicate, SyntaxProviderTransform)
				.Where(static method => method != default)
				.Collect()
				.SelectMany(static (methods, cancellationToken) => methods.GroupBy(static method => method.node.Parent as TypeDeclarationSyntax, TypeIdentifierEqualityComparer.Instance))
				.Where(static grouping => grouping.Key is not null)!;

			context.RegisterSourceOutput(provider, SourceOutputAction);
		}

		private static void PostInitializationCallback(IncrementalGeneratorPostInitializationContext context)
		{
			context.AddSource("HelloWorldAttribute.g.cs", SourceText.From(helloWorldAttribute, Encoding.UTF8));
		}

		private static bool SyntaxProviderPredicate(SyntaxNode syntaxNode, CancellationToken cancellationToken)
		{
			return syntaxNode is MethodDeclarationSyntax
				{
					ParameterList.Parameters.Count: 0,
				} method
				&& method.Modifiers.Any(SyntaxKind.PartialKeyword);
		}

		private static (MethodDeclarationSyntax node, IMethodSymbol symbol) SyntaxProviderTransform(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
		{
			var method = (MethodDeclarationSyntax)context.TargetNode;
			var methodSymbol = (IMethodSymbol)context.TargetSymbol;

			Debug.Assert(method.AttributeLists.Count > 0);
			Debug.Assert(methodSymbol.IsPartialDefinition);

			if (methodSymbol.ReturnType.SpecialType == SpecialType.System_String)
			{
				return (method, methodSymbol);
			}

			return default;
		}

		private static void SourceOutputAction(SourceProductionContext context, IGrouping<TypeDeclarationSyntax, (MethodDeclarationSyntax node, IMethodSymbol symbol)> candidates)
		{
			INamedTypeSymbol typeSymbol = candidates.First().symbol.ContainingType;

			StringBuilder builder = new();
			using StringWriter writer = new(builder, CultureInfo.InvariantCulture);
			using IndentedTextWriter source = new(writer, "\t");

			source.WriteLine("// <auto-generated/>");
			source.WriteLine("#nullable enable");
			source.WriteLine();

			if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
			{
				source.WriteLine($"namespace {typeSymbol.ContainingNamespace}");
				source.WriteLine("{");
				source.Indent++;
			}

			source.WriteLine($"partial {candidates.Key.Keyword} {candidates.Key.Identifier.ValueText}");
			source.WriteLine("{");
			source.Indent++;

			foreach ((MethodDeclarationSyntax node, IMethodSymbol symbol) candidate in candidates)
			{
				source.WriteLine($@"{candidate.node.Modifiers} string {candidate.node.Identifier.ValueText}() => ""Hello, World!"";");
			}

			source.Indent--;
			source.WriteLine("}");

			if (!typeSymbol.ContainingNamespace.IsGlobalNamespace)
			{
				source.Indent--;
				source.WriteLine("}");
			}

			Debug.Assert(source.Indent == 0);

			context.AddSource($"{candidates.Key.Identifier.ValueText}.HelloWorld.g.cs", writer.ToString());
		}
	}
}
#endif
